# Generated by Django 4.2.10 on 2024-02-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.SmallIntegerField(choices=[(1, 'Ежедневно'), (2, 'Каждые два дня'), (3, 'Каждые три дня'), (7, 'Еженедельно')], default=1, verbose_name='Периодичность'),
        ),
    ]
