# Generated by Django 4.2.10 on 2024-02-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0004_alter_habit_related_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='nice_habit',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак приятной привычки'),
        ),
    ]
