# Generated by Django 4.2.10 on 2024-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0008_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(blank=True, choices=[('Полезная', 'Полезная'), ('Приятная', 'Приятная')], max_length=100, null=True, verbose_name='Название привычки'),
        ),
    ]
