# Generated by Django 4.2.10 on 2024-02-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='telegram_id'),
        ),
    ]
